version: '3'

networks:
  frontend:
    external: true

services:
  app:
    image: registry.justmammoth.us/csgoscan/csgoscan:latest
    restart: unless-stopped
    networks:
      - frontend
    environment:
      STEAM_API_KEY: ${STEAM_API_KEY}
      FACEIT_API_KEY: ${FACEIT_API_KEY}
