name: Build image and run deployment

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push as latest
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/csgoscan:latest
      - name: Build and push as ${{ github.ref_name }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/csgoscan:${{ github.ref_name }}

  deploy:
    needs: [build-and-push]
    uses: felixcapuano/server-deployment/.github/workflows/trigger_deployment.yml@main
    with:
      name: csgoscan
      repository: ${{ github.repository }}
      branch: main
      file: docker-compose.yml
      environment: |
        IMAGE_VERSION=${{ github.ref_name }}
        STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}
        FACEIT_API_KEY=${{ secrets.FACEIT_API_KEY }}
    secrets: inherit
