name: Run deployment

on:
  workflow_dispatch:
    inputs:
      image_version:
        required: false
        default: latest
        description: image version

env:
  ENVIRONMENT: |
    IMAGE_VERSION=${{ inputs.image_version }}
    STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}
    FACEIT_API_KEY=${{ secrets.FACEIT_API_KEY }}

jobs:
  deploy:
    uses: justmammoth-us/server-actions/.github/workflows/stack_deployment.yml@main
    with:
      name: csgoscan
      repository: ${{ github.repository }}
      branch: main
      file: docker-compose.yml
    secrets:
      DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
      environment: ${{ env.ENVIRONMENT }}
