name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push as latest
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/csgoscan:latest
      - name: Build and push as ${{ github.ref }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/csgoscan:${{ github.ref }}
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run playbook
  #       uses: dawidd6/action-ansible-playbook@v2
  #       with:
  #         playbook: deploy.yml
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         inventory: |
  #           [all]
  #           ${{ secrets.}}
  #         options: --extra-vars hello=there
