name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: latest

jobs:
  deploy:
    uses: felixcapuano/server-deployment/.github/workflows/trigger_deployment.yml@main
    with:
      name: csgoscan
      repository: ${{ github.repository }}
      branch: main
      file: docker-compose.yml
      environment: |
        IMAGE_VERSION=${{ inputs.version }}
        STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}
        FACEIT_API_KEY=${{ secrets.FACEIT_API_KEY }}
    secrets: inherit
